export const genreList = [
  "",
  "Astronomy",
  "Behavioral science",
  "Biology",
  "Chemistry",
  "Physics",
  "Earth sciences",
  "Mathematics",
  "Computer science",
  "Anthropology",
  "Social science",
  "Archaeology",
  "Communications",
  "Economics",
  "Ethnology",
  "Geography",
  "Political science",
  "Psychology",
  "Semiotics",
  "Sociology",
  "Humanities",
  "Art",
  "Classics",
  "Creative writing",
  "Dance",
  "English literature",
  "Folklore",
  "History",
  "Linguistics",
  "Literature and cultural studies",
  "Music",
  "Mythology",
  "Philology",
  "Philosophy",
  "Religious studies",
  "Theatre",
  "Women's studies and gender studies",
  "Architecture and environmental design",
  "Business",
  "Education",
  "Engineering",
  "Ergonomics",
  "Agriculture",
  "Forestry",
  "Family and consumer science",
  "Journalism and mass communications",
  "Law",
  "Library and information science",
  "Health sciences",
  "Military science",
  "Public affairs and community service",
];
